//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions:
//
// cbuffer FrameBuffer::PerFrame
// {
//
//   row_major float4x4 FrameBuffer::CameraView;// Offset:    0 Size:    64 [unused]
//   row_major float4x4 FrameBuffer::CameraProj;// Offset:   64 Size:    64 [unused]
//   row_major float4x4 FrameBuffer::CameraViewProj;// Offset:  128 Size:    64
//   row_major float4x4 FrameBuffer::CameraViewProjUnjittered;// Offset:  192 Size:    64 [unused]
//   row_major float4x4 FrameBuffer::CameraPreviousViewProjUnjittered;// Offset:  256 Size:    64 [unused]
//   row_major float4x4 FrameBuffer::CameraProjUnjittered;// Offset:  320 Size:    64 [unused]
//   row_major float4x4 FrameBuffer::CameraProjUnjitteredInverse;// Offset:  384 Size:    64 [unused]
//   row_major float4x4 FrameBuffer::CameraViewInverse;// Offset:  448 Size:    64 [unused]
//   row_major float4x4 FrameBuffer::CameraViewProjInverse;// Offset:  512 Size:    64 [unused]
//   row_major float4x4 FrameBuffer::CameraProjInverse;// Offset:  576 Size:    64 [unused]
//   float4 FrameBuffer::CameraPosAdjust;// Offset:  640 Size:    16 [unused]
//   float4 FrameBuffer::CameraPreviousPosAdjust;// Offset:  656 Size:    16 [unused]
//   float4 FrameBuffer::FrameParams;   // Offset:  672 Size:    16 [unused]
//   float4 FrameBuffer::DynamicResolutionParams1;// Offset:  688 Size:    16 [unused]
//   float4 FrameBuffer::DynamicResolutionParams2;// Offset:  704 Size:    16 [unused]
//
// }
//
// cbuffer PerGeometry
// {
//
//   float4 ShadowFadeParam;            // Offset:    0 Size:    16 [unused]
//   row_major float4x4 World;          // Offset:   16 Size:    64
//   float4 EyePos;                     // Offset:   80 Size:    16 [unused]
//   float4 WaterParams;                // Offset:   96 Size:    16 [unused]
//   float4 TreeParams;                 // Offset:  112 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerGeometry                       cbuffer      NA          NA            cb2      1
// FrameBuffer::PerFrame             cbuffer      NA          NA           cb12      1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB12[12], immediateIndexed
dcl_constantbuffer CB2[5], immediateIndexed
dcl_input v0.xyz
dcl_output_siv o0.xyzw, position
dcl_temps 3
mul [precise] r0.xyzw, cb12[10].xxxx, cb2[1].xyzw
mul [precise] r1.xyzw, cb12[10].yyyy, cb2[2].xyzw
add [precise] r0.xyzw, r0.xyzw, r1.xyzw
mul [precise] r1.xyzw, cb12[10].zzzz, cb2[3].xyzw
add [precise] r0.xyzw, r0.xyzw, r1.xyzw
mul [precise] r1.xyzw, cb12[10].wwww, cb2[4].xyzw
add [precise] r0.xyzw, r0.xyzw, r1.xyzw
mov r1.xyz, v0.xyzx
mov r1.w, l(1.000000)
dp4 r0.x, r0.xyzw, r1.xyzw
add o0.z, r0.x, l(5.000000)
mul [precise] r0.xyzw, cb12[8].xxxx, cb2[1].xyzw
mul [precise] r2.xyzw, cb12[8].yyyy, cb2[2].xyzw
add [precise] r0.xyzw, r0.xyzw, r2.xyzw
mul [precise] r2.xyzw, cb12[8].zzzz, cb2[3].xyzw
add [precise] r0.xyzw, r0.xyzw, r2.xyzw
mul [precise] r2.xyzw, cb12[8].wwww, cb2[4].xyzw
add [precise] r0.xyzw, r0.xyzw, r2.xyzw
dp4 o0.x, r0.xyzw, r1.xyzw
mul [precise] r0.xyzw, cb12[9].xxxx, cb2[1].xyzw
mul [precise] r2.xyzw, cb12[9].yyyy, cb2[2].xyzw
add [precise] r0.xyzw, r0.xyzw, r2.xyzw
mul [precise] r2.xyzw, cb12[9].zzzz, cb2[3].xyzw
add [precise] r0.xyzw, r0.xyzw, r2.xyzw
mul [precise] r2.xyzw, cb12[9].wwww, cb2[4].xyzw
add [precise] r0.xyzw, r0.xyzw, r2.xyzw
dp4 o0.y, r0.xyzw, r1.xyzw
mul [precise] r0.xyzw, cb12[11].xxxx, cb2[1].xyzw
mul [precise] r2.xyzw, cb12[11].yyyy, cb2[2].xyzw
add [precise] r0.xyzw, r0.xyzw, r2.xyzw
mul [precise] r2.xyzw, cb12[11].zzzz, cb2[3].xyzw
add [precise] r0.xyzw, r0.xyzw, r2.xyzw
mul [precise] r2.xyzw, cb12[11].wwww, cb2[4].xyzw
add [precise] r0.xyzw, r0.xyzw, r2.xyzw
dp4 o0.w, r0.xyzw, r1.xyzw
ret
// Approximately 36 instruction slots used
